dist: artifacts
before:
   hooks:
     - go mod download
builds:
  - id: http-check
    main: ./cmd/http-check/main.go
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - freebsd
    goarch:
    - amd64
    - arm
    - arm64
    ignore:
    - goos: freebsd
      goarch: arm64
    ldflags: -s -w -X main.version={{.Version}}
    binary: http-check
  - id: http-check-server
    main: ./cmd/http-check-server/main.go
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - freebsd
    goarch:
    - amd64
    - arm
    - arm64
    ignore:
    - goos: freebsd
      goarch: arm64
    ldflags: -s -w -X main.version={{.Version}}
    binary: http-check-server