version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout

      - run: 
          name: build client
          command: go build
          working_directory: cmd/http-check
      - run: 
          name: build server
          command: go build
          working_directory: cmd/http-check-server
      - run: 
          name: run tests
          command: go test -v -cover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)
