// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ExpectedStatusCode   []uint32 `protobuf:"varint,6,rep,packed,name=expected_status_code,json=expectedStatusCode,proto3" json:"expected_status_code,omitempty"`
	ExpectedBody         string   `protobuf:"bytes,7,opt,name=expected_body,json=expectedBody,proto3" json:"expected_body,omitempty"`
	CertExpireDays       uint32   `protobuf:"varint,8,opt,name=cert_expire_days,json=certExpireDays,proto3" json:"cert_expire_days,omitempty"`
	Debug                bool     `protobuf:"varint,9,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetExpectedStatusCode() []uint32 {
	if m != nil {
		return m.ExpectedStatusCode
	}
	return nil
}

func (m *Request) GetExpectedBody() string {
	if m != nil {
		return m.ExpectedBody
	}
	return ""
}

func (m *Request) GetCertExpireDays() uint32 {
	if m != nil {
		return m.CertExpireDays
	}
	return 0
}

func (m *Request) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage         string   `protobuf:"bytes,3,opt,name=debug_message,json=debugMessage,proto3" json:"debug_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetDebugMessage() string {
	if m != nil {
		return m.DebugMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x6f, 0xfa, 0x9b, 0xfa, 0x36, 0xa8, 0xb2, 0xba, 0xb0, 0xba, 0x8a, 0x0a, 0x8b, 0xac,
	0x2a, 0x04, 0x1b, 0xd6, 0x14, 0x24, 0x36, 0x6c, 0xdc, 0x07, 0x88, 0x1c, 0x7b, 0xd4, 0x56, 0xd0,
	0xda, 0x64, 0x1c, 0x68, 0xde, 0x85, 0x87, 0x45, 0x19, 0xc7, 0xdd, 0xf9, 0xfb, 0x8e, 0x7c, 0x34,
	0x9a, 0x61, 0x19, 0x42, 0xfd, 0x7d, 0xd4, 0xb0, 0x71, 0xb5, 0xf5, 0x96, 0x0f, 0x5c, 0xb5, 0xfe,
	0x1d, 0xb0, 0xa9, 0x84, 0xaf, 0x06, 0xd0, 0xf3, 0x15, 0x4b, 0x29, 0xd0, 0xf6, 0x53, 0x24, 0x79,
	0x52, 0xcc, 0xe4, 0x95, 0x39, 0x67, 0xa3, 0x83, 0x45, 0x2f, 0x06, 0xe4, 0xe9, 0xdd, 0x39, 0xa7,
	0xfc, 0x41, 0x0c, 0x83, 0xeb, 0xde, 0x5d, 0x47, 0x83, 0x50, 0x9f, 0xd5, 0x09, 0xc4, 0x28, 0x74,
	0x44, 0xa6, 0x7e, 0x85, 0xf8, 0x63, 0x6b, 0x23, 0xc6, 0x7d, 0x7f, 0xcf, 0xfc, 0x9e, 0x2d, 0xe1,
	0xe2, 0x40, 0x7b, 0x30, 0x25, 0x7a, 0xe5, 0x1b, 0x2c, 0xb5, 0x35, 0x20, 0x26, 0xf9, 0xb0, 0xc8,
	0x24, 0x8f, 0xd9, 0x8e, 0xa2, 0xad, 0x35, 0xc0, 0x6f, 0x59, 0x76, 0xfd, 0x51, 0x59, 0xd3, 0x8a,
	0x29, 0x55, 0xce, 0xa3, 0x7c, 0xb6, 0xa6, 0xe5, 0x05, 0x5b, 0x68, 0xa8, 0x7d, 0x09, 0x17, 0x77,
	0xac, 0xa1, 0x34, 0xaa, 0x45, 0x91, 0xe6, 0x49, 0x91, 0xc9, 0x9b, 0xce, 0xbf, 0x92, 0x7e, 0x51,
	0x2d, 0xf2, 0x25, 0x1b, 0x1b, 0xa8, 0x9a, 0xbd, 0x98, 0xe5, 0x49, 0x91, 0xca, 0x00, 0x6b, 0xcd,
	0x52, 0x09, 0xe8, 0xec, 0x19, 0x81, 0x0b, 0x36, 0xc5, 0x46, 0x6b, 0x40, 0xa4, 0xed, 0xa4, 0x32,
	0x62, 0x97, 0x9c, 0x00, 0x51, 0xed, 0xa1, 0xdf, 0x4f, 0xc4, 0x6e, 0x48, 0x2a, 0x2a, 0x63, 0x1e,
	0x76, 0x35, 0x27, 0xf9, 0x1e, 0xdc, 0xc3, 0x13, 0x5b, 0xbc, 0x79, 0xef, 0xb6, 0x07, 0xd0, 0x1f,
	0xbb, 0x70, 0x21, 0x7e, 0xc7, 0xc6, 0xc4, 0xfc, 0xff, 0xc6, 0x55, 0x9b, 0xfe, 0x42, 0xab, 0x79,
	0x80, 0x30, 0xd0, 0xfa, 0x5f, 0x35, 0xa1, 0xfb, 0x3c, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x21,
	0xce, 0x56, 0x5f, 0xd9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HttpCheckServiceClient is the client API for HttpCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HttpCheckServiceClient interface {
	Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type httpCheckServiceClient struct {
	cc *grpc.ClientConn
}

func NewHttpCheckServiceClient(cc *grpc.ClientConn) HttpCheckServiceClient {
	return &httpCheckServiceClient{cc}
}

func (c *httpCheckServiceClient) Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.HttpCheckService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpCheckServiceServer is the server API for HttpCheckService service.
type HttpCheckServiceServer interface {
	Check(context.Context, *Request) (*Response, error)
}

// UnimplementedHttpCheckServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHttpCheckServiceServer struct {
}

func (*UnimplementedHttpCheckServiceServer) Check(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterHttpCheckServiceServer(s *grpc.Server, srv HttpCheckServiceServer) {
	s.RegisterService(&_HttpCheckService_serviceDesc, srv)
}

func _HttpCheckService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpCheckServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HttpCheckService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpCheckServiceServer).Check(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _HttpCheckService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HttpCheckService",
	HandlerType: (*HttpCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HttpCheckService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
