on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build http-check
      run: go build
      working-directory: ./cmd/http-check
    - name: Build http-check-server
      run: go build
      working-directory: ./cmd/http-check-server
    - name: Run tests
      run: go test ./... -v -covermode=count
